# Generated by Django 5.0.4 on 2024-05-03 11:44

import core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', core.models.UUIDPrimaryKeyField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=30)),
                ('hashed_credentials', models.CharField(max_length=255)),
                ('verified_on', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', core.models.CreatedOnField(auto_now_add=True)),
                ('last_modified_on', core.models.LastModifiedOnField(auto_now=True)),
            ],
            options={
                'db_table': 'user_account',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', core.models.UUIDPrimaryKeyField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=1024)),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('file_size', models.PositiveBigIntegerField()),
                ('file_creation_ts', models.DateTimeField()),
                ('file_modification_ts', models.DateTimeField()),
                ('last_checked_on', models.DateTimeField(blank=True, null=True)),
                ('last_synchronized_on', models.DateTimeField(blank=True, null=True)),
                ('created_on', core.models.CreatedOnField(auto_now_add=True)),
                ('last_modified_on', core.models.LastModifiedOnField(auto_now=True)),
            ],
            options={
                'db_table': 'document',
                'indexes': [models.Index(fields=['file_name'], name='document_file_na_c72421_idx'), models.Index(fields=['file_creation_ts'], name='document_file_cr_aa25c1_idx')],
            },
        ),
        migrations.CreateModel(
            name='InferenceLog',
            fields=[
                ('id', core.models.UUIDPrimaryKeyField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input', models.JSONField()),
                ('output', models.JSONField()),
                ('created_on', core.models.CreatedOnField(auto_now_add=True)),
                ('last_modified_on', core.models.LastModifiedOnField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.useraccount')),
            ],
            options={
                'db_table': 'inference_log',
                'indexes': [models.Index(fields=['created_on'], name='inference_l_created_bc508b_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', core.models.UUIDPrimaryKeyField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('device_name', models.CharField(blank=True, max_length=255)),
                ('expires_on', models.DateTimeField(blank=True, null=True)),
                ('last_auth_on', models.DateTimeField(blank=True, null=True)),
                ('created_on', core.models.CreatedOnField(auto_now_add=True)),
                ('last_modified_on', core.models.LastModifiedOnField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to='core.useraccount')),
            ],
            options={
                'db_table': 'auth_token',
                'indexes': [models.Index(fields=['expires_on'], name='auth_token_expires_cf99ae_idx'), models.Index(fields=['last_auth_on'], name='auth_token_last_au_a279f7_idx')],
            },
        ),
    ]
