# Generated by Django 5.0.4 on 2024-05-03 11:47

import core.auth
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='token',
            field=models.CharField(default=core.auth.generate_token, max_length=255, unique=True),
        ),
    ]
