# Generated by Django 5.0.4 on 2024-05-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='last_checked_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='last_synchronized_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
