# Generated by Django 5.0.4 on 2024-05-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_document_last_checked_ts_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='document',
            name='document_file_ha_c9291e_idx',
        ),
        migrations.AlterField(
            model_name='document',
            name='file_hash',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
