# Generated by Django 5.0.4 on 2024-05-03 10:24

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_document_document_file_ha_c9291e_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InferenceLog',
            fields=[
                ('id', core.models.UUIDPrimaryKeyField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input', models.JSONField()),
                ('output', models.JSONField()),
                ('created_on', core.models.CreatedOnField(auto_now_add=True)),
                ('last_modified_on', core.models.LastModifiedOnField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inference_log',
                'indexes': [models.Index(fields=['created_on'], name='inference_l_created_bc508b_idx')],
            },
        ),
    ]
